In [90]:
import pandas as pd
import pymongo
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import numpy as np

# Connect to MongoDB
CWL = "..."
SNUM = ...

connection_string = f"mongodb://{CWL}:a{SNUM}@localhost:27017/{CWL}"
client = pymongo.MongoClient(connection_string, serverSelectionTimeoutMS=5000)

# test that the tunnel/database connection works
client.admin.command("ping")
print("Connected to MongoDB.")

db = client[CWL]
movies_collection = db["movies"]

Connected to MongoDB.

### Research Question 1

In [91]:
# RQ1 Analysis Query
pipeline1 = [
    {
        "$match": {
            "genre": {"$in": ["Horror", "Action", "Comedy"]},
            "box_office.domestic_gross": {"$ne": None},
            "box_office.foreign_gross": {"$ne": None}
        }
    },
    {
        "$project": {
            "_id": 0,
            "imdb_title_id": 1,
            "title": 1,
            "year": 1,
            "genre": 1,
            "num_recommendations": {"$size": "$reddit_mentions"},
            "domestic_gross": "$box_office.domestic_gross",
            "foreign_gross": "$box_office.foreign_gross",
            "total_revenue": {
                "$add": [
                    "$box_office.domestic_gross",
                    "$box_office.foreign_gross"
                ]
            }
        }
    },
    {
        "$addFields": {
            "domestic_share": {
                "$cond": [
                    {"$eq": ["$total_revenue", 0]},
                    None,
                    {"$divide": ["$domestic_gross", "$total_revenue"]}
                ]
            },
            "foreign_share": {
                "$cond": [
                    {"$eq": ["$total_revenue", 0]},
                    None,
                    {"$divide": ["$foreign_gross", "$total_revenue"]}
                ]
            }
        }
    },
    {
        "$sort": {"num_recommendations": -1}
    }
]

results1 = list(movies_collection.aggregate(pipeline1))
df1 = pd.DataFrame(results1)

print(df1.columns.tolist())
df1.head()

['imdb_title_id', 'title', 'year', 'genre', 'num_recommendations', 'domestic_gross', 'foreign_gross', 'total_revenue', 'domestic_share', 'foreign_share']

,imdb_title_id,title,year,genre,num_recommendations,domestic_gross,foreign_gross,total_revenue,domestic_share,foreign_share
0,tt1375666,inception,2010,"[Action, Adventure, Sci-Fi]",462,292576195,542948447,835524642,0.350171,0.649829
1,tt2911666,john wick,2014,"[Action, Crime, Thriller]",316,43037835,33197166,76235001,0.564542,0.435458
2,tt6499752,upgrade,2018,"[Action, Sci-Fi, Thriller]",292,11977130,4576155,16553285,0.723550,0.276450
3,tt5688932,sorry to bother you,2018,"[Comedy, Fantasy, Sci-Fi]",292,17493096,792464,18285560,0.956662,0.043338
4,tt1856101,blade runner 2049,2017,"[Action, Drama, Mystery]",280,92054159,167303249,259357408,0.354932,0.645068

In [92]:
# Compare MongoDB and SQL results
sql_df = pd.read_csv("rq1.csv", skiprows = [2])

mongo_df = df1.copy()  
mongo_df = mongo_df.drop(columns=["_id"], errors="ignore")

# clean column names
sql_df.columns = sql_df.columns.str.strip().str.lower()
mongo_df.columns = mongo_df.columns.str.strip().str.lower()

# check structure
print("SQL columns:", sql_df.columns.tolist())
print("Mongo columns:", mongo_df.columns.tolist())

SQL columns: ['imdb_title_id', 'title', 'year', 'genre', 'num_recommendations', 'domestic_gross', 'foreign_gross', 'total_revenue', 'foreign_share']
Mongo columns: ['imdb_title_id', 'title', 'year', 'genre', 'num_recommendations', 'domestic_gross', 'foreign_gross', 'total_revenue', 'domestic_share', 'foreign_share']

In [93]:
print("SQL shape:", sql_df.shape)
print("Mongo shape:", mongo_df.shape)

SQL shape: (448, 9)
Mongo shape: (415, 10)

In [94]:
# RQ1 Visualization Query
pipeline1_1 = [
    {
        "$match": {
            "genre": {"$in": ["Horror", "Action", "Comedy"]},
            "box_office.domestic_gross": {"$ne": None},
            "box_office.foreign_gross": {"$ne": None}
        }
    },

    # compute totals + shares
    {
        "$addFields": {
            "total_revenue": {
                "$add": [
                    "$box_office.domestic_gross",
                    "$box_office.foreign_gross"
                ]
            }
        }
    },
    {
        "$addFields": {
            "domestic_share": {
                "$cond": [
                    {"$eq": ["$total_revenue", 0]},
                    None,
                    {"$divide": ["$box_office.domestic_gross", "$total_revenue"]}
                ]
            },
            "foreign_share": {
                "$cond": [
                    {"$eq": ["$total_revenue", 0]},
                    None,
                    {"$divide": ["$box_office.foreign_gross", "$total_revenue"]}
                ]
            }
        }
    },
    {
        "$addFields": {
            "num_recommendations": {"$size": "$reddit_mentions"}
        }
    },

    # explode genre (like pandas explode)
    {"$unwind": "$genre"},

    {
        "$match": {
            "genre": {"$in": ["Horror", "Action", "Comedy"]}
        }
    },

    # convert data to long format
    {
        "$project": {
            "genre": 1,
            "num_recommendations": 1,
            "market_data": [
                {"market": "Domestic", "share": "$domestic_share"},
                {"market": "International", "share": "$foreign_share"}
            ]
        }
    },

    {"$unwind": "$market_data"},

    # final grouping
    {
        "$group": {
            "_id": {
                "genre": "$genre",
                "market": "$market_data.market",
                "num_recommendations": "$num_recommendations"
            },
            "avg_share": {"$avg": "$market_data.share"}
        }
    },

    {
        "$project": {
            "_id": 0,
            "genre": "$_id.genre",
            "market": "$_id.market",
            "num_recommendations": "$_id.num_recommendations",
            "avg_share": 1
        }
    },

    {
        "$sort": {
            "genre": 1,
            "market": 1,
            "num_recommendations": 1
        }
    }
]

results_grouped = list(movies_collection.aggregate(pipeline1_1))
df_grouped = pd.DataFrame(results_grouped)

df_grouped.head()

   avg_share   genre    market  num_recommendations
0   0.392174  Action  Domestic                    0
1   0.605260  Action  Domestic                    1
2   0.408586  Action  Domestic                    2
3   0.520675  Action  Domestic                    3
4   0.442025  Action  Domestic                    4

In [119]:
# RQ1 Visualization
rq1_viz = (
    alt.Chart(df_grouped)
    .mark_line(point=True)
    .encode(
        x=alt.X("num_recommendations:Q", title="Number of Reddit Recommendations"),
        y=alt.Y("avg_share:Q", title="Average Revenue Share", scale=alt.Scale(domain=[0, 1])),
        color=alt.Color("market:N", title="Market")
    )
    .properties(width=220, height=220)
    .facet(
        column=alt.Column("genre:N", title="Genre")
    )
    .properties(
        title=alt.TitleParams(
            text=[
                "How Reddit Recommendation Frequency",
                "Relates to International and Domestic Revenue Share"
            ],
            anchor="middle",  
            fontSize=18
        )
    )
)

rq1_viz
rq1_viz

alt.FacetChart(...)

### Research Question 2

In [86]:
# RQ2 Analysis Query
pipeline2= [
	{
        "$match": {
            "box_office.domestic_gross": {"$ne": None},
            "box_office.foreign_gross": {"$ne": None},
            "num_reddit_mentions": {"$gt": 0}
		}
	},
	{
        "$project": {
            "_id": 0,
            "total_gross": {
                "$add": [
                    "$box_office.domestic_gross",
                    "$box_office.foreign_gross"
                ]
            },
            "avg_vote": 1,
            "reddit_discussion_count": {"$size":"$reddit_mentions"}
        }
    },
]

results2 = list(movies_collection.aggregate(pipeline2))
df2 = pd.DataFrame(results2)

df2.head(10)

Empty DataFrame
Columns: []
Index: []

In [87]:
# Compare MongoDB and SQL results
sql2_df = pd.read_csv("rq2.csv", skiprows = [2])

mongo2_df = df2.copy()  

mongo2_df = mongo2_df.drop(columns=["_id"], errors="ignore")

# clean column names 
sql2_df.columns = sql2_df.columns.str.strip().str.lower()
mongo2_df.columns = mongo2_df.columns.str.strip().str.lower()

# check structure
print("SQL columns:", sql2_df.columns.tolist())
print("Mongo columns:", mongo2_df.columns.tolist())

AttributeError: Can only use .str accessor with string values!

In [96]:
print("SQL shape:", sql2_df.shape)
print("Mongo shape:", mongo2_df.shape)

SQL shape: (342, 3)
Mongo shape: (0, 0)

In [97]:
# RQ2 Visualization

# Selecting the variables of the scatter plot
avg_vote = mongo2_df[["avg_vote"]]
total_gross = mongo2_df[["total_gross"]]
reddit_discussion_count = mongo2_df[["reddit_discussion_count"]]

# Combining the 2 scatter plots
fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=(10, 5))

# Plotting a scatter plot to visualize the relation between avg_vote and total_gross
ax1 = plt.subplot(1, 2, 1)
plt.scatter(avg_vote, total_gross, alpha=0.5)
plt.title("Average Vote on IMDB vs Total Gross")
plt.ylabel("Total Gross")
plt.xlabel("Average Vote on IMDb")

# Plotting a scatter plot to visualize the relation between reddit_discussion_count and total_gross
ax2 = plt.subplot(1, 2, 2)
plt.scatter(reddit_discussion_count, total_gross, alpha=0.5)
plt.title("Reddit Discussion Count vs Total Gross")
plt.ylabel("Total Gross")
plt.xlabel("Reddit Discussion Count")

plt.tight_layout()
plt.show()

KeyError: "None of [Index(['avg_vote'], dtype='object')] are in the [columns]"

### Research Question 3

In [98]:
test = [
    {
        "$project": {"_id": 0}
    }
]

In [99]:
# RQ3 Analysis Query
pipeline3 = [
    {
        "$unwind": {"path": "$reddit_mentions"}},
    {
        "$unwind": {"path": "$genre"}},
    {
        "$match": {
            "genre": {
                "$in": ["Horror", "Action", 'Comedy']
            }
        }
    },
    {
        "$addFields": {
            "duration_bin": {
                "$cond": {
                    "if": {"$lt": ["$duration", 60]},
                    "then": "<60",
                    "else": "$duration_bin"
                }
            }
        }
    },
    {
        "$addFields": {
            "duration_bin": {
                "$cond": {
                    "if": {
                        "$and": [
                            {"$gte": ["$duration", 60]},
                            {"$lte": ["$duration", 80]}
                        ]},
                    "then": "60-79",
                    "else": "$duration_bin" 
                }
            }
        }
    },
    {
        "$addFields": {
            "duration_bin": {
                "$cond": {
                    "if": {
                        "$and": [
                            {"$gte": ["$duration", 80]},
                            {"$lt": ["$duration", 100]}
                        ]},
                    "then": "80-99",
                    "else": "$duration_bin" 
                }
            }
        }
    },
    {
        "$addFields": {
            "duration_bin": {
                "$cond": {
                    "if": {
                        "$and": [
                            {"$gte": ["$duration", 100]},
                            {"$lt": ["$duration", 120]}
                        ]},
                    "then": "100-119",
                    "else": "$duration_bin" 
                }
            }
        }
    },
    {
        "$addFields": {
            "duration_bin": {
                "$cond": {
                    "if": {
                        "$and": [
                            {"$gte": ["$duration", 120]},
                            {"$lt": ["$duration", 140]}
                        ]},
                    "then": "120-139",
                    "else": "$duration_bin" 
                }
            }
        }
    },
    {
        "$addFields": {
            "duration_bin": {
                "$cond": {
                    "if": {
                        "$and": [
                            {"$gte": ["$duration", 140]},
                            {"$lt": ["$duration", 160]}
                        ]},
                    "then": "140-159",
                    "else": "$duration_bin" 
                }
            }
        }
    },
    {
        "$addFields": {
            "duration_bin": {
                "$cond": {
                    "if": {
                        "$and": [
                            {"$gte": ["$duration", 160]},
                            {"$lt": ["$duration", 180]}
                        ]},
                    "then": "160-179",
                    "else": "$duration_bin" 
                }
            }
        }
    },
    {
        "$addFields": {
            "duration_bin": {
                "$cond": {
                    "if": {
                        "$and": [
                            {"$gte": ["$duration", 180]},
                            {"$lte": ["$duration", 200]}
                        ]},
                    "then": "180-200",
                    "else": "$duration_bin" 
                }
            }
        }
    },
    {
        "$addFields": {
            "duration_bin": {
                "$cond": {
                    "if": {"$gt": ["$duration", 200]},
                    "then": ">200",
                    "else": "$duration_bin" 
                }
            }
        }
    },
    {
        "$group": {
            "_id": {"genre": "$genre",
                    "duration_bin": "$duration_bin"
            },
            "avg_upvotes": {"$avg": "$reddit_mentions.upvotes"
            }
        }
    },
    {
        "$project": {
            "_id": 0,
            "avg_upvotes": 1,
            "genre": "$_id.genre",
            "duration_bin": "$_id.duration_bin"
        }
    }
]
            
# $sort 

results3 = list(movies_collection.aggregate(pipeline3))
df3 = pd.DataFrame(results3)

print(df3.columns)
df3.head(10)

Index(['avg_upvotes', 'genre', 'duration_bin'], dtype='object')

   avg_upvotes   genre duration_bin
0     2.063291  Comedy        60-79
1     2.922673  Action      140-159
2     3.028713  Comedy      120-139
3     1.865385  Action        60-79
4     3.452747  Horror        60-79
5     1.000000  Action      180-200
6     2.904331  Action      120-139
7     3.797814  Comedy      140-159
8     2.991708  Action      100-119
9     2.954467  Horror      100-119

In [100]:
# Compare MongoDB and SQL results
sql3_df = pd.read_csv("rq3.csv", skiprows = [2])

mongo3_df = df3.copy()  

mongo3_df = mongo3_df.drop(columns=["_id"], errors="ignore")

# clean column names 
sql3_df.columns = sql3_df.columns.str.strip().str.lower()
mongo3_df.columns = mongo3_df.columns.str.strip().str.lower()

# check structure
print("SQL columns:", sql3_df.columns.tolist())
print("Mongo columns:", mongo3_df.columns.tolist())

SQL columns: ['duratio', 'genre_', 'avg_upvotes']
Mongo columns: ['avg_upvotes', 'genre', 'duration_bin']

In [101]:
print("SQL shape:", sql3_df.shape)
print("Mongo shape:", mongo3_df.shape)

SQL shape: (19, 3)
Mongo shape: (19, 3)

In [102]:
sql3 = sql3_df.rename(columns={"duratio": "duration_bin", "genre_": "genre"})

# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.join.html
combined = df3.join(sql3.set_index(["genre", "duration_bin"]), on = ["genre", "duration_bin"], 
                    lsuffix = "_mongodb", rsuffix = "_SQL")

# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html
# https://www.geeksforgeeks.org/python/change-the-order-of-a-pandas-dataframe-columns-in-python/
combined[["genre", "duration_bin", "avg_upvotes_SQL", "avg_upvotes_mongodb"]].sort_values("avg_upvotes_mongodb")

     genre duration_bin avg_upvotes_SQL  avg_upvotes_mongodb
5   Action      180-200               1             1.000000
3   Action        60-79             NaN             1.865385
0   Comedy        60-79             NaN             2.063291
13  Comedy      160-179      2.14814815             2.148148
11  Action        80-99             NaN             2.735610
6   Action      120-139      2.84772647             2.904331
10  Comedy        80-99             NaN             2.906957
1   Action      140-159             NaN             2.922673
18  Horror        80-99             NaN             2.944244
9   Horror      100-119      2.95446698             2.954467
8   Action      100-119      3.03298376             2.991708
2   Comedy      120-139      2.94551845             3.028713
14  Comedy      100-119      2.99564033             3.054235
17  Horror      120-139      3.24313023             3.243130
15  Horror      140-159      3.39779006             3.397790
4   Horror        60-79             NaN             3.452747
7   Comedy      140-159       4.1971831             3.797814
16  Comedy      180-200               4             4.000000
12  Action      160-179       4.1004902             4.100490

In [89]:
# RQ3 Visualization
# line plot 
# drawing on relationships
alt.Chart(df3).mark_line().encode(x = "duration_bin", y = "avg_upvotes",
                                color = "genre").properties(width = 500)

alt.Chart(...)